name: Deploy-GHPage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: GH Pages Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm ci
          CI=false npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
